// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package main - types.go holds the public API types for the folio WASM module.
This file has no build constraint so that tygo can generate TypeScript
definitions from it without requiring GOOS=js GOARCH=wasm.
*/

/**
 * RenderSettings is the JSON payload passed as the second argument to folioRender().
 */
export interface RenderSettings {
  pageSize: string;
  mediaType: string;
  pdfProfile: string;
  pdfTitle: string;
  ignoreResourceErrors: boolean;
  cssDpi: number /* int */;
  watermark?: string;
  headerHtml?: string;
  footerHtml?: string;
  streamingThreshold: number /* int */; // 0 = auto (default 500 pages)
  benchmark: boolean;
  /**
   * Large-scale render options (renderPagesBatched).
   * "auto" means pilot-derived; a number overrides.
   */
  batchSize?: any; // int | "auto"
  maxWorkers?: any; // int | "auto"
  tmpDir?: string;
  fresh?: boolean;
  maxAttempts?: number /* int */; // default 3
  notify?: boolean;
  emptyItemPolicy?: string; // "blank"|"skip"|"abort"
  expectedPages?: number /* int */; // hint for browser guard
  keepTmpFiles?: boolean; // keep per-batch PDFs after merge (JS-side only)
  /**
   * FontBaseDir is a filesystem directory path. When set (Node.js only),
   * the HTML converter resolves @font-face url() paths relative to this
   * directory - no base64 encoding needed. Ignored in browser environments.
   */
  fontBaseDir?: string;
}
/**
 * RenderResult is the object returned by folioRender() on success.
 */
export interface RenderResult {
  /**
   * PDF is the base64-encoded PDF bytes.
   */
  pdf: string;
  pages: number /* int */;
  size: number /* int */;
  width: number /* float64 */;
  height: number /* float64 */;
  benchmark?: BenchmarkSpan[];
}
/**
 * RenderError is the object returned by folioRender() when rendering fails.
 */
export interface RenderError {
  error: string;
}
/**
 * BenchmarkSpan records the duration of one named phase during rendering.
 */
export interface BenchmarkSpan {
  name: string;
  ms: number /* int64 */;
}
/**
 * FolioMergeStreamToResult is returned by folioMergeStreamTo() on success.
 */
export interface FolioMergeStreamToResult {
  pages: number /* int */;
  size: number /* int64 */;
}
