/**
 * Generates the sheet font stylesheet + runtime registry at dev/build time from
 * data/sheet-fonts.json (curation: id, cssFamily, family) joined with
 * data/fonts-manifest.json (provenance: files/weights per family, owned by
 * scripts/copy-fonts.mjs). Add a font by editing data/sheet-fonts.json — no
 * code changes needed.
 *
 * Outputs (regenerated on every dev/build run, safe to commit like routeTree.gen.ts):
 *   web/src/css/generated/sheet-fonts.css       @font-face rules + Tailwind @theme font-<id> vars
 *   web/src/features/sheet/generated/sheet-fonts.json    per-id { cssFamily, files }
 *   web/src/features/sheet/generated/sheet-font-ids.ts   the id union, as a const array
 *   web/src/features/sheet/generated/font-data/<id>.ts   per-id { file: base64 data URI },
 *     gitignored — precomputes what the Folio PDF capture needs to embed
 *     every font it uses as a data URI (the wasm worker can't resolve a
 *     relative /fonts/... URL itself), so renderSheetHTML.tsx's font loader
 *     never has to fetch+base64-encode a font at render time.
 */
import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'

const WEIGHT_MAP: Record<string, number> = { regular: 400, medium: 400, bold: 700 }

interface ManifestFile {
  file: string
  weight: string
  sha256: string
}
interface ManifestFamily {
  family: string
  files: ManifestFile[]
}
interface Manifest {
  families: ManifestFamily[]
}
interface Curation {
  fonts: { id: string; cssFamily: string; family: string }[]
}

interface FontFile {
  dir: string
  file: string
  weight: number
  style: string
  version: string
}
interface FontDef {
  id: string
  cssFamily: string
  files: FontFile[]
}

const GENERATED_HEADER =
  '// AUTO-GENERATED by web/vite-plugins/sheet-fonts.ts from data/sheet-fonts.json + data/fonts-manifest.json.\n' +
  '// Do not edit by hand — add fonts in data/sheet-fonts.json instead.\n'

function readFonts(repoRoot: string): FontDef[] {
  const manifest: Manifest = JSON.parse(
    fs.readFileSync(path.join(repoRoot, 'data/fonts-manifest.json'), 'utf-8'),
  )
  const curation: Curation = JSON.parse(
    fs.readFileSync(path.join(repoRoot, 'data/sheet-fonts.json'), 'utf-8'),
  )
  const byFamily = new Map(manifest.families.map((f) => [f.family, f]))

  return curation.fonts.map(({ id, cssFamily, family }) => {
    const manifestFamily = byFamily.get(family)
    if (!manifestFamily) {
      throw new Error(
        `data/sheet-fonts.json: family "${family}" (id "${id}") is not in data/fonts-manifest.json`,
      )
    }
    return {
      id,
      cssFamily,
      files: manifestFamily.files.map((f) => ({
        dir: family,
        file: f.file,
        weight: WEIGHT_MAP[f.weight] ?? 400,
        style: 'normal',
        // scripts/copy-fonts.mjs's sha256 — the sole source of truth for
        // this file's version, so re-running the copy without byte changes
        // never bumps it (see file-version.ts's mtime-vs-content note).
        version: f.sha256.slice(0, 10),
      })),
    }
  })
}

/**
 * `?v=<sha256>` on the url() busts the browser's HTTP cache when a font
 * file's content changes under the same name. sheet-fonts.css itself is
 * content-hashed by Vite's CSS bundling, so it's already safe; it's the raw
 * /fonts/... file underneath (served verbatim from public/) that isn't.
 */
function buildCss(fonts: FontDef[]): string {
  const faces = fonts.flatMap((def) =>
    def.files.map(
      (f) =>
        `@font-face{font-family:'${def.cssFamily}';font-style:${f.style};` +
        `font-weight:${f.weight};font-display:swap;` +
        `src:url('/fonts/${f.dir}/${f.file}?v=${f.version}') format('truetype');}`,
    ),
  )
  const themeVars = fonts.map((def) => {
    const fallback = def.cssFamily === 'Noto Serif Hebrew' ? 'serif' : "'Noto Serif Hebrew', serif"
    return `  --font-${def.id}: '${def.cssFamily}', ${fallback};`
  })
  return [
    '/* AUTO-GENERATED by web/vite-plugins/sheet-fonts.ts — do not edit by hand.',
    ' * Add fonts in data/sheet-fonts.json (+ data/fonts-manifest.json). */',
    ...faces,
    '',
    '@theme {',
    ...themeVars,
    '}',
    '',
  ].join('\n')
}

function mimeFor(file: string): string {
  const ext = file.split('.').pop()?.toLowerCase()
  if (ext === 'woff2') return 'font/woff2'
  if (ext === 'woff') return 'font/woff'
  if (ext === 'otf') return 'font/otf'
  return 'font/truetype'
}

/** `{ file: data URI }` for one font id — read from the same /fonts/<dir>/<file> the browser @font-face rules point at. */
function buildFontDataModule(def: FontDef, publicDir: string): string {
  const entries = def.files.map((f) => {
    const bytes = fs.readFileSync(path.join(publicDir, 'fonts', f.dir, f.file))
    const dataUri = `data:${mimeFor(f.file)};base64,${bytes.toString('base64')}`
    return `  '${f.file}': '${dataUri}',`
  })
  return (
    GENERATED_HEADER +
    `const data: Record<string, string> = {\n${entries.join('\n')}\n}\n\nexport default data\n`
  )
}

function buildRegistryJson(fonts: FontDef[]): string {
  const byId = Object.fromEntries(fonts.map((f) => [f.id, { id: f.id, cssFamily: f.cssFamily, files: f.files }]))
  return JSON.stringify(byId, null, 2) + '\n'
}

function buildIdsTs(fonts: FontDef[]): string {
  // SHEET_FONT_CLASS values are literal `font-<id>` strings (not built with a
  // template literal) so Tailwind's static class scanner can see them as-is.
  const classEntries = fonts.map((f) => `  '${f.id}': 'font-${f.id}',`)
  return (
    GENERATED_HEADER +
    `export const SHEET_FONT_IDS = ${JSON.stringify(fonts.map((f) => f.id))} as const\n\n` +
    `export const SHEET_FONT_CLASS: Record<(typeof SHEET_FONT_IDS)[number], string> = {\n` +
    `${classEntries.join('\n')}\n}\n`
  )
}

function writeIfChanged(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf-8') === content) return
  fs.writeFileSync(filePath, content)
}

export function sheetFonts(): Plugin {
  let repoRoot: string
  let publicDir: string
  let cssOut: string
  let jsonOut: string
  let idsOut: string
  let fontDataDir: string

  const generate = () => {
    const fonts = readFonts(repoRoot)
    writeIfChanged(cssOut, buildCss(fonts))
    writeIfChanged(jsonOut, buildRegistryJson(fonts))
    writeIfChanged(idsOut, buildIdsTs(fonts))
    for (const def of fonts) {
      writeIfChanged(path.join(fontDataDir, `${def.id}.ts`), buildFontDataModule(def, publicDir))
    }
  }

  return {
    name: 'izkor:sheet-fonts',
    configResolved(config) {
      repoRoot = path.resolve(config.root, '..')
      publicDir = path.join(config.root, 'public')
      cssOut = path.join(config.root, 'src/css/generated/sheet-fonts.css')
      jsonOut = path.join(config.root, 'src/features/sheet/generated/sheet-fonts.json')
      idsOut = path.join(config.root, 'src/features/sheet/generated/sheet-font-ids.ts')
      fontDataDir = path.join(config.root, 'src/features/sheet/generated/font-data')
    },
    buildStart() {
      generate()
    },
    configureServer(server) {
      const watched = [
        path.join(repoRoot, 'data/sheet-fonts.json'),
        path.join(repoRoot, 'data/fonts-manifest.json'),
      ]
      server.watcher.add(watched)
      server.watcher.on('change', (file) => {
        if (watched.includes(file)) generate()
      })
    },
  }
}
