/**
 * Writes src/features/folio/generated/wasm-version.ts with a cache-busting
 * version per file in public/wasm/, derived from each file's mtime.
 *
 * public/wasm/folio.wasm and wasm_exec.js are fetched by folio.worker.ts with
 * hardcoded absolute paths (importScripts/fetch can't go through Vite's
 * import graph, so they get none of its content-hash cache busting). The
 * service worker's CacheFirst rule for /wasm/* (vite.config.ts) then pins
 * whatever it fetched first — after a `folio.wasm` rebuild, browsers with an
 * old SW/HTTP cache entry keep running the stale binary indefinitely, with no
 * signal that anything is wrong. Appending `?v=<mtime>` makes a rebuilt
 * binary a new URL, so both caches fetch it fresh.
 */
import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'

import { fileVersion } from './file-version.ts'

const WASM_FILES = ['wasm_exec.js', 'folio.wasm']

const GENERATED_HEADER =
  '// AUTO-GENERATED by web/vite-plugins/wasm-version.ts — do not edit by hand.\n'

function buildVersionMap(wasmDir: string): Record<string, string> {
  return Object.fromEntries(WASM_FILES.map((file) => [file, fileVersion(path.join(wasmDir, file))]))
}

function writeIfChanged(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, 'utf-8') === content) return
  fs.writeFileSync(filePath, content)
}

export function wasmVersion(): Plugin {
  let wasmDir: string
  let out: string

  const generate = () => {
    const versions = buildVersionMap(wasmDir)
    writeIfChanged(
      out,
      `${GENERATED_HEADER}export const WASM_VERSION: Record<string, string> = ${JSON.stringify(versions, null, 2)}\n`,
    )
  }

  return {
    name: 'izkor:wasm-version',
    configResolved(config) {
      wasmDir = path.join(config.root, 'public/wasm')
      out = path.join(config.root, 'src/features/folio/generated/wasm-version.ts')
    },
    buildStart() {
      generate()
    },
    configureServer(server) {
      server.watcher.add(wasmDir)
      server.watcher.on('change', (file) => {
        if (path.dirname(file) === wasmDir) generate()
      })
    },
  }
}
