/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnAccessibilityRouteImport } from './routes/en/accessibility'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnPrivacyRouteImport } from './routes/en/privacy'
import { Route as WizardIndexRouteImport } from './routes/wizard/index'
import { Route as EnBlogIndexRouteImport } from './routes/en/blog/index'
import { Route as EnBlogSlugRouteImport } from './routes/en/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAccessibilityRoute = EnAccessibilityRouteImport.update({
  id: '/en/accessibility',
  path: '/en/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/en/privacy',
  path: '/en/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardIndexRoute = WizardIndexRouteImport.update({
  id: '/wizard/',
  path: '/wizard/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogIndexRoute = EnBlogIndexRouteImport.update({
  id: '/en/blog/',
  path: '/en/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogSlugRoute = EnBlogSlugRouteImport.update({
  id: '/en/blog/$slug',
  path: '/en/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/accessibility': typeof EnAccessibilityRoute
  '/en/contact': typeof EnContactRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/blog/': typeof BlogIndexRoute
  '/en/': typeof EnIndexRoute
  '/wizard/': typeof WizardIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/accessibility': typeof EnAccessibilityRoute
  '/en/contact': typeof EnContactRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/blog': typeof BlogIndexRoute
  '/en': typeof EnIndexRoute
  '/wizard': typeof WizardIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/blog': typeof EnBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/accessibility': typeof EnAccessibilityRoute
  '/en/contact': typeof EnContactRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/blog/': typeof BlogIndexRoute
  '/en/': typeof EnIndexRoute
  '/wizard/': typeof WizardIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/privacy'
    | '/blog/$slug'
    | '/en/about'
    | '/en/accessibility'
    | '/en/contact'
    | '/en/privacy'
    | '/blog/'
    | '/en/'
    | '/wizard/'
    | '/en/blog/$slug'
    | '/en/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/privacy'
    | '/blog/$slug'
    | '/en/about'
    | '/en/accessibility'
    | '/en/contact'
    | '/en/privacy'
    | '/blog'
    | '/en'
    | '/wizard'
    | '/en/blog/$slug'
    | '/en/blog'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/privacy'
    | '/blog/$slug'
    | '/en/about'
    | '/en/accessibility'
    | '/en/contact'
    | '/en/privacy'
    | '/blog/'
    | '/en/'
    | '/wizard/'
    | '/en/blog/$slug'
    | '/en/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EnAboutRoute: typeof EnAboutRoute
  EnAccessibilityRoute: typeof EnAccessibilityRoute
  EnContactRoute: typeof EnContactRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  WizardIndexRoute: typeof WizardIndexRoute
  EnBlogSlugRoute: typeof EnBlogSlugRoute
  EnBlogIndexRoute: typeof EnBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/accessibility': {
      id: '/en/accessibility'
      path: '/en/accessibility'
      fullPath: '/en/accessibility'
      preLoaderRoute: typeof EnAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/en/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard/': {
      id: '/wizard/'
      path: '/wizard'
      fullPath: '/wizard/'
      preLoaderRoute: typeof WizardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/': {
      id: '/en/blog/'
      path: '/en/blog'
      fullPath: '/en/blog/'
      preLoaderRoute: typeof EnBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/$slug': {
      id: '/en/blog/$slug'
      path: '/en/blog/$slug'
      fullPath: '/en/blog/$slug'
      preLoaderRoute: typeof EnBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  BlogSlugRoute: BlogSlugRoute,
  EnAboutRoute: EnAboutRoute,
  EnAccessibilityRoute: EnAccessibilityRoute,
  EnContactRoute: EnContactRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  BlogIndexRoute: BlogIndexRoute,
  EnIndexRoute: EnIndexRoute,
  WizardIndexRoute: WizardIndexRoute,
  EnBlogSlugRoute: EnBlogSlugRoute,
  EnBlogIndexRoute: EnBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
