/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as ToolsFolioRouteImport } from './routes/tools/folio'
import { Route as ToolsSystemRouteImport } from './routes/tools/system'
import { Route as WizardIndexRouteImport } from './routes/wizard/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFolioRoute = ToolsFolioRouteImport.update({
  id: '/tools/folio',
  path: '/tools/folio',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSystemRoute = ToolsSystemRouteImport.update({
  id: '/tools/system',
  path: '/tools/system',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardIndexRoute = WizardIndexRouteImport.update({
  id: '/wizard/',
  path: '/wizard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/tools/folio': typeof ToolsFolioRoute
  '/tools/system': typeof ToolsSystemRoute
  '/wizard/': typeof WizardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/tools/folio': typeof ToolsFolioRoute
  '/tools/system': typeof ToolsSystemRoute
  '/wizard': typeof WizardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/tools/folio': typeof ToolsFolioRoute
  '/tools/system': typeof ToolsSystemRoute
  '/wizard/': typeof WizardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/tools/folio'
    | '/tools/system'
    | '/wizard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/tools/folio'
    | '/tools/system'
    | '/wizard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/tools/folio'
    | '/tools/system'
    | '/wizard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ToolsFolioRoute: typeof ToolsFolioRoute
  ToolsSystemRoute: typeof ToolsSystemRoute
  WizardIndexRoute: typeof WizardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/folio': {
      id: '/tools/folio'
      path: '/tools/folio'
      fullPath: '/tools/folio'
      preLoaderRoute: typeof ToolsFolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/system': {
      id: '/tools/system'
      path: '/tools/system'
      fullPath: '/tools/system'
      preLoaderRoute: typeof ToolsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard/': {
      id: '/wizard/'
      path: '/wizard'
      fullPath: '/wizard/'
      preLoaderRoute: typeof WizardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ToolsFolioRoute: ToolsFolioRoute,
  ToolsSystemRoute: ToolsSystemRoute,
  WizardIndexRoute: WizardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
