import path from 'node:path'
import tailwindcss from '@tailwindcss/vite'
import { tanstackRouter } from '@tanstack/router-plugin/vite'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

import { pdfCss } from './vite-plugins/pdf-css.ts'
import { sheetFonts } from './vite-plugins/sheet-fonts.ts'
import { wasmVersion } from './vite-plugins/wasm-version.ts'

export default defineConfig({
  plugins: [
    tanstackRouter({
      routesDirectory: './src/routes',
      generatedRouteTree: './src/routeTree.gen.ts',
    }),
    react(),
    tailwindcss(),
    sheetFonts(),
    pdfCss(),
    wasmVersion(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.svg', 'icons.svg'],
      manifest: {
        name: 'תפילה לנשמה — דף תפילה לקריאה בבית העלמין',
        short_name: 'תפילה לנשמה',
        description: 'בניית דף תפילה מהודר להדפסה — תהילים, קדיש, משניות והשכבה — לקריאה בבית העלמין',
        lang: 'he',
        dir: 'rtl',
        theme_color: '#141a2e',
        background_color: '#ffffff',
        display: 'standalone',
        start_url: '/',
        scope: '/',
        icons: [
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
          {
            src: '/icons/maskable-icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,ttf,otf}'],
        // font-data/* chunks (base64-embedded fonts for the Folio PDF
        // capture, see vite-plugins/sheet-fonts.ts) are NOT precached, same
        // reasoning as folio.wasm below — precaching all ~20 fonts on
        // install would defeat the point of only loading the 2-3 a given
        // sheet actually uses. Cached lazily via runtimeCaching instead.
        globIgnores: ['**/wasm/**', 'assets/font-data/**'],
        // SPA: every navigation offline serves the app shell (routes render
        // client-side from the URL).
        navigateFallback: '/index.html',
        runtimeCaching: [
          {
            // folio.wasm (16 MB) is NOT precached — see P6-03 report note.
            // After the first PDF render it is cached here for offline reuse.
            urlPattern: /\/wasm\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'folio-wasm',
              expiration: { maxEntries: 3, maxAgeSeconds: 60 * 60 * 24 * 30 },
            },
          },
          {
            urlPattern: /\/assets\/font-data\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'sheet-font-data',
              expiration: { maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 30 },
            },
          },
        ],
      },
      devOptions: {
        enabled: true,
        type: 'module',
      },
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(import.meta.dirname, './src'),
    },
  },
  build: {
    rollupOptions: {
      output: {
        // Route the lazy per-font base64 chunks (fonts.ts's import.meta.glob,
        // generated by vite-plugins/sheet-fonts.ts) into their own directory
        // so the PWA config above can precisely exclude them from SW
        // precache — see the workbox globIgnores/runtimeCaching entries.
        chunkFileNames: (chunkInfo) => {
          const isFontData = chunkInfo.moduleIds.some((id) => id.includes('/generated/font-data/'))
          return isFontData ? 'assets/font-data/[name]-[hash].js' : 'assets/[name]-[hash].js'
        },
      },
    },
  },
})
